apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: nginx-helloworld
              image: nginx:1.16
        ports:
        - containerPort: 8080
        envfrom:
        - configMapRef: 
            name: myconfigmapv1.0
