apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld
    tier: web
spec:

  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello
    tier: web
  type: LoadBalancer